env:
  TEXT2IMAGE_MODEL_NAME: "Tongyi-MAI/Z-Image-Turbo"
  TEXT2IMAGE_BASE_URL: "base_url/v1"
  TEXT2IMAGE_API_KEY: "mlis token"
  IMAGE_RESOLUTION: "512x512"
  MCP_TEXT_TO_IMAGE_SERVER_NAME: "text2image-mcp"
  MCP_ALLOWED_HOSTS: "text2image-mcp.${DOMAIN_NAME}"

image:
  repository: fcaliva/text-to-image-mcp-app
  pullPolicy: Always
  tag: 0.0.1

replicaCount: 1

service:
  type: ClusterIP
  port: 8000
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
      
ezua:
  enabled: true
  virtualService:
    endpoint: "text2image-mcp.${DOMAIN_NAME}"
    istioGateway: "istio-system/ezaf-gateway"

certificatesPolicy:
  enabled: true

  env:
    - name: SSL_CERT_DIR
      value: /etc/ssl/certs
    - name: REQUESTS_CA_BUNDLE
      value: /tmp/certs/ca-certificates.crt
    - name: SSL_CERT_FILE
      value: /tmp/certs/ca-certificates.crt
    - name: AIOHTTP_CLIENT_SESSION_SSL
      value: /tmp/certs/ca-certificates.crt
    - name: CURL_CA_BUNDLE
      value: /tmp/certs/ca-certificates.crt

  initContainer:
    image: alpine:3.20
    command:
      - /bin/sh
      - -c
      - |
        set -e
        if [ -f /etc/ssl/certs/ca-certificates.crt ]; then
          cp /etc/ssl/certs/ca-certificates.crt /work/ca-certificates.crt
        elif [ -f /etc/ssl/certs/ca-bundle.crt ]; then
          cp /etc/ssl/certs/ca-bundle.crt /work/ca-certificates.crt
        else
          echo "No base CA bundle found in init container"
          exit 1
        fi
        cat /config/ezaf-root-ca.crt >> /work/ca-certificates.crt
        echo "" >> /work/ca-certificates.crt

  initVolumeMounts:
    - name: combined-certs
      mountPath: /work
    - name: ezaf-root-ca
      mountPath: /config/ezaf-root-ca.crt
      subPath: ca-certificates.crt
      readOnly: true

  volumeMounts:
    - name: combined-certs
      mountPath: /tmp/certs
      readOnly: false

  volumes:
    - name: combined-certs
      emptyDir: {}
    - name: ezaf-root-ca
      configMap:
        name: ezaf-root-ca
        items:
          - key: ezaf-root-ca.crt
            path: ca-certificates.crt