import json
from typing import Any

import pandas as pd

from mcp_instance import mcp
from schema import FacetPlotKind, PlotKind, PlotRequest
from utils import (
    _basic_stats,
    _describe_numeric,
    _df_from_records,
    _jsonable_dict,
    _jsonable_records,
    _profile_dataframe,
    _validate_columns,
)
from renderers import (
    _render_plotly_html,
    _render_seaborn_html_mpld3,
)
from renderers.seaborn import _prepare_pie_data


def _to_json_string(payload: dict[str, Any]) -> str:
    return json.dumps(
        payload,
        indent=2,
        ensure_ascii=False,
        default=str,
    )


def _infer_vegalite_type(df: pd.DataFrame, col: str) -> str:
    if pd.api.types.is_numeric_dtype(df[col]):
        return "quantitative"

    if pd.api.types.is_datetime64_any_dtype(df[col]):
        return "temporal"

    if pd.api.types.is_bool_dtype(df[col]):
        return "nominal"

    return "nominal"


def _to_chart_json(req: PlotRequest, df: pd.DataFrame) -> dict[str, Any]:
    encoding: dict[str, Any] = {}

    if req.x and req.x in df.columns:
        encoding["x"] = {
            "field": req.x,
            "type": _infer_vegalite_type(df, req.x),
        }

    if req.y and req.y in df.columns:
        encoding["y"] = {
            "field": req.y,
            "type": _infer_vegalite_type(df, req.y),
        }

    if req.hue and req.hue in df.columns:
        encoding["color"] = {
            "field": req.hue,
            "type": _infer_vegalite_type(df, req.hue),
        }

    if req.size and req.size in df.columns:
        encoding["size"] = {
            "field": req.size,
            "type": _infer_vegalite_type(df, req.size),
        }

    mark_by_kind = {
        "scatter": "point",
        "line": "line",
        "histogram": "bar",
        "kde": "area",
        "box": "boxplot",
        "violin": "density",
        "bar": "bar",
        "count": "bar",
        "regression": "point+line",
        "residual": "point",
        "correlation_heatmap": "rect",
        "pair": "matrix",
        "facet": "facet",
        "pie": "arc",
    }

    return {
        "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
        "description": req.title
        or f"{req.kind} chart generated by statistical-visualization-mcp",
        "mark": mark_by_kind.get(req.kind, "point"),
        "encoding": encoding,
        "metadata": {
            "source_library": "seaborn",
        },
    }


def _build_plot_spec(req: PlotRequest) -> dict[str, Any]:
    return {
        "library": "seaborn",
        "kind": req.kind,
        "x": req.x,
        "y": req.y,
        "hue": req.hue,
        "size": req.size,
        "style": req.style,
        "row": req.row,
        "col": req.col,
        "title": req.title,
        "bins": req.bins,
    }


def _build_response(req: PlotRequest, df: pd.DataFrame) -> dict[str, Any]:
    warnings: list[str] = []

    missing = _validate_columns(
        df,
        [req.x, req.y, req.hue, req.size, req.style, req.row, req.col],
    )

    if missing:
        return {
            "status": "error",
            "kind": req.kind,
            "error": f"Missing columns: {missing}",
            "available_columns": df.columns.tolist(),
            "warnings": [],
        }

    plotly_html = None
    seaborn_mpld3_html = None

    try:
        plotly_html = _render_plotly_html(req, df)
    except Exception as exc:
        warnings.append(f"Could not render Plotly HTML: {exc}")

    try:
        seaborn_mpld3_html = _render_seaborn_html_mpld3(req, df)
    except Exception as exc:
        warnings.append(f"Could not render seaborn mpld3 HTML: {exc}")

    stats = _basic_stats(df, req.x, req.y, req.hue)

    if req.kind == "pie":
        try:
            pie_df = _prepare_pie_data(df, req.x, req.y)
            stats["pie_summary"] = _jsonable_records(pie_df)
        except Exception as exc:
            warnings.append(f"Could not compute pie summary: {exc}")

    return {
        "status": "ok",
        "kind": req.kind,
        "plot_spec": _build_plot_spec(req),
        "data_profile": _profile_dataframe(df),
        "stats": stats,
        "chart_json": _to_chart_json(req, df),
        "sampled_data": _jsonable_records(df.head(req.max_return_rows)),
        "html": {
            "plotly": plotly_html,
            "seaborn_mpld3": seaborn_mpld3_html,
        },
        "warnings": warnings,
    }


def _make_request(
    *,
    data: list[dict[str, Any]],
    kind: PlotKind,
    x: str | None = None,
    y: str | None = None,
    hue: str | None = None,
    size: str | None = None,
    style: str | None = None,
    row: str | None = None,
    col: str | None = None,
    title: str | None = None,
    bins: int | None = None,
    max_return_rows: int = 500,
) -> PlotRequest:
    return PlotRequest(
        data=data,
        kind=kind,
        x=x,
        y=y,
        hue=hue,
        size=size,
        style=style,
        row=row,
        col=col,
        title=title,
        bins=bins,
        max_return_rows=max_return_rows,
    )


@mcp.tool()
def health_check() -> str:
    """
    Check whether the statistical visualization MCP server is alive.

    The LLM should use this tool only when it needs to verify that the visualization
    server is reachable before calling plotting tools.
    """
    return _to_json_string({"status": "ok"})


@mcp.tool()
def list_supported_plots() -> str:
    """
    List all available visualization tools and when the LLM should use each one.

    Use this tool when the user asks what kinds of charts are supported, or when the
    agent needs to choose the best visualization for a dataset and analytical question.
    """
    return _to_json_string(
        {
            "status": "ok",
            "tools": {
                "summarize_dataset": "Profile a dataset before choosing a chart.",
                "create_plot": "Generic plotting tool when the chart kind is already known.",
                "scatter_plot": "Use for relationships between two numeric variables, optionally colored by category.",
                "line_plot": "Use for trends over ordered values, time, or sequence-like x-axis values.",
                "histogram_plot": "Use for distribution of a single numeric variable.",
                "kde_plot": "Use for smooth distribution curves of numeric variables.",
                "box_plot": "Use for comparing distributions and outliers across categories.",
                "violin_plot": "Use for comparing distribution shape across categories.",
                "bar_plot": "Use for aggregated category comparisons.",
                "count_plot": "Use for frequency counts of categories.",
                "regression_plot": "Use for numeric relationship with an estimated linear trend.",
                "residual_plot": "Use for diagnosing linear-regression fit and non-linear patterns.",
                "correlation_heatmap": "Use for correlation matrix across numeric variables.",
                "pair_plot": "Use for broad exploratory analysis across multiple numeric variables.",
                "facet_plot": "Use for small-multiple charts split by row and/or column categories.",
                "pie_chart": "Use for part-to-whole composition across categories.",
            },
            "output_guide": {
                "html": "Every plotting tool returns interactive HTML under the 'html' key "
                "(plotly and/or seaborn_mpld3 backends). No PNG/base64 images are produced.",
            },
        }
    )


@mcp.tool()
def summarize_dataset(data: list[dict[str, Any]]) -> str:
    """
    Summarize a tabular dataset before plotting.

    The LLM should use this tool before choosing a visualization when it needs to inspect
    column names, data types, missing values, numeric summaries, category counts, or sample
    rows. This tool does not create a chart; it returns dataset metadata and descriptive
    statistics as JSON.
    """
    try:
        df = _df_from_records(data)

        return _to_json_string(
            {
                "status": "ok",
                "data_profile": _profile_dataframe(df),
                "numeric_summary": _describe_numeric(df),
                "sample_rows": _jsonable_records(df.head(20)),
                "warnings": [],
            }
        )

    except Exception as exc:
        return _to_json_string(
            {
                "status": "error",
                "error": str(exc),
                "warnings": [],
            }
        )


@mcp.tool()
def create_plot(
    request: dict[str, Any],
) -> str:
    """
    Create a statistical visualization using a generic request object.

    The LLM should use this tool when it already knows the desired chart kind and wants
    a single flexible interface. Supported kinds include scatter, line, histogram, kde,
    box, violin, bar, count, regression, residual, correlation_heatmap, pair, and facet.

    The response includes chart_json for LLM reasoning, interactive HTML (Plotly and/or
    seaborn mpld3), statistics, dataset profile, and warnings.
    """
    try:
        req = PlotRequest(**request)
        df = _df_from_records(req.data)
        return _to_json_string(_build_response(req, df))

    except Exception as exc:
        return _to_json_string(
            {
                "status": "error",
                "error": str(exc),
                "warnings": [],
            }
        )